---
bluetooth_ping_command: hcitool_check.sh
bluetooth_devices:
- 00:11:22:33:44:55
- 66:77:88:99:aa:bb
trigger_only_on_all: false
triggers:
  - name: run_prog_1
    type: exec
    enabled: true
    on_present: /bin/true
    on_absent: /bin/true
  - name: call_url_2
    type: url
    enabled: false
    on_present: http://localhost:8080/present
    on_absent: http://localhost:8080/absent

